### ISSUE TITLE
Use a non-experimental repostiory as default

### ISSUE THREAD

**Issue by vlipiainen** [executablebooks/sphinx-thebe#54]
### Context

- Binderhub needs a github repostiory to create an environment for interactive code. The default, as defined [here](https://github.com/executablebooks/sphinx-thebe/blob/aec1ec48a98ceac0acaad4d5ac23e86a6047498b/sphinx_thebe/__init__.py#L126-L128), is [`jupyter-stacks-datascience`](https://github.com/binder-examples/jupyter-stacks-datascience).
- The repostiory above states that "🛑🛑This is an experimental repository. It might change or be deleted without notice!🛑🛑". This means that sphinx-thebe might stop working without warning.

### Proposal

There are two main directions for a fix:
1) Make the `jupyter-stacks-datascience` repository more stable
2) Use some other default, such as `https://github.com/binder-examples/requirements`

Constraints & discussion
- We might not be able to affect the experimental status of `jupyter-stacks-datascience`
- I'm not sure what I picked above is a good default.

### Tasks and updates

- [ ] Decide between the two solutions
- [ ] If changing the default, pick the new default
- [ ] Make the small code change
